GET http://localhost:5000/api/kategori

###

GET http://localhost:5000/api/kategori/6

###

POST http://localhost:5000/api/kategori
Content-Type: application/json

{
  "kategori_name": "mencuri",
}

###
DELETE http://localhost:5000/api/kategori/4

###
PUT http://localhost:5000/api/kategori/2
Content-Type: application/json

{
  "kategori_name": "joget"
}