GET http://localhost:5000/todos

###
GET http://localhost:5000/todos/3

###
POST http://localhost:5000/todos
Content-Type: application/json

{
  "title": "Belajar",
  "user_id": "1"
}

###

DELETE http://localhost:5000/todos/1

###
PUT http://localhost:5000/todos/3
Content-Type: application/json

{
  "tittle": "done",
  "user_id": "3"
}